<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <PeakGameDir Condition="'$(PeakGameDir)' == '' and '$(PEAK_GAME_DIR)' != ''">$(PEAK_GAME_DIR)</PeakGameDir>
  </PropertyGroup>
  <Import Project="PeakGameDir.props" Condition="Exists('PeakGameDir.props')" />
</Project>
